### ISSUE TITLE
Add `ToMoatType` instance for `NonEmpty`

### ISSUE THREAD

**Issue by glasserc** [MercuryTechnologies/moat#53]
This type represents a non-empty list (at least one element). It exists in `base`, although it isn't supported uniformly well across the ecosystem. In particular, see https://github.com/codedownio/aeson-typescript/pull/30. I don't know if other languages have support for this kind of concept, but at the very least, we could probably serialize it the same way we serialize possibly-empty lists.

**Comment by chessai** [comment]
I think the two best options are:
(1) serialise as a regular list (`[a]`)
(2) serialise as a two-tuple of the head and the rest of the list (`(a, [a])`)

`5 :| [1, 3]` in json with encoding (2) would look like
```json
[
  5,
  [ 1, 3 ]
]
```

**Comment by chessai** [comment]
I think the two best options are:
(1) serialise as a regular list (`[]`)
(2) serialise as a two-tuple of the head and the rest of the list (`(a, [])`)

`5 :| [1, 3]` in json with encoding (2) would look like
```json
[
  5,
  [ 1, 3 ]
]
```

**Comment by chessai** [comment]
Another option is use the best-case (in terms of type safety) thing for each language.
- Swift has a library for NonEmpty collections: https://github.com/pointfreeco/swift-nonempty
- Kotlin has one in `arrows`: https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-non-empty-list/
- I couldn't quickly find a TypeScript library for NonEmpty arrays, but it looks like it's pretty easy to implement: `type NonEmptyArray<T> = [T, ...T[]]` (playground link: https://www.typescriptlang.org/play?#code/C4TwDgpgBAcg9gOwKIFsygIICcsEMQA8AKgHxQC8UA2kQDRQB0TRVAuqwFAcDGiAzsCgQ0mHAC5YiVOhDY8hAJLBhZSmygB6DUJxwsUQDLkPfoOEy5AJglz8BJSorVWm7XADWUQKDkULgDMArgjcwACWiEIAHpDB8Mgisjj4ABS44pJx5omEgW4IcADuCCQAlFAA3hxQVVC8CHxwADYQDA1wAOZJAOQ2IFB5UABuuNwAt3Cd9KlYxRwAvlwQURAxUvE9SWylWpJQYP4QACYQfLu4fKlQUxBtrYPDYwyGC0srGaLyG524DW2Bd61YTqsLauDzeLjbIjgaAAcX8qQOHACQVC4RCfFi0lABAwJBSaR6OJKEimUHR6SxCXkRIq1SgWAgwH8WAQlxwLQgCDawAAFlAyAAGOZ+QLBMKstqMuT4rASTFrLIEARYEJckrlSr0xnM1lTADcwuMdUEUwAzI4qJ0AIxAjjbOkAPQA-BwQr4oEl0fKZDLTcVSrSoJLgNKzcUDfa6VVnXMgA)

Note that using libraries would not be without precedent, since the Swift backend already uses the `Tagged` library. And for Kotlin, `arrows` is pretty common.

This kind of goes back to a common design point with many libraries/tools similar to `moat`: it would be nice to have some configurability if someone doesn't want these types, without having to define newtypes. But there aren't many users of `moat` outside Mercury, so there isn't much demand for this, I believe.

**Comment by tadfisher** [comment]
I don't want to encode dependent types for client code, personally. I did open https://github.com/MercuryTechnologies/moat/pull/54 to just encode these as `Array` to match Aeson's default codegen. If we want to enforce the type dependency, we can encode these to `MoatAlias` and have each client implement their own setup to enforce the non-empty constraint.

**Comment by friedbrice** [comment]
Closed by

**Comment by friedbrice** [comment]
sorry <.< unintentional

**Comment by friedbrice** [comment]
I agree with Chessai and with Tad.

> Use the best-case ... thing for each language.

Yep.

> I don't want to encode dependent types for client code, personally.

Yes, though I'd have phrased this as "If it requires and external library, then we shouldn't consider it idiomatic Kotlin."

**Comment by friedbrice** [comment]
I think we should merge https://github.com/MercuryTechnologies/moat/pull/54 for right now and close this issue.

I think we should add a followup issue that provides support for Swift, by adding a constructor to `MoatType`. I don't think we should require our Kotlin users to depend on Arrow, however I might feel about Arrow personally.

**Comment by tadfisher** [comment]
Done in #54
